-- MySQL Script generated by MySQL Workbench
-- Fri Mar 15 17:16:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------	
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
use `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
-- Creación de la tabla Estado
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
use `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
-- Creación de la tabla Estado
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `activo` int (1) not null,
  `detalles` VARCHAR(250) NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- Creación de la tabla TipoUsuario
CREATE TABLE IF NOT EXISTS `mydb`.tipo_usuario (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipousuario` VARCHAR(30) NOT NULL,
   `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TipoUsuario_Estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Creación de la tabla TipoDocumento
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TipoDocumento_Estado`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla usuario
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
   `estado` INT NOT null,
   `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `tipo_usuario` INT NOT NULL,
  `tipo_documento` INT NOT NULL,
  PRIMARY KEY (`id`),
  
  CONSTRAINT `fk_usuario_TipoUsuario`
    FOREIGN KEY (`Tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_TipoDocumento1`
    FOREIGN KEY (`Tipo_documento`)
    REFERENCES `mydb`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Usuario_Estado`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    
) ENGINE = InnoDB;


-- Creación de la tabla Horario
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(45) NOT NULL,
  `hora_inicio` TIME NULL,
  `hora_final` TIME NULL,
  `detalles` VARCHAR(250) NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Horario_Estado`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

select*from Usuario;
-- Creación de la tabla TipoCurso
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_curso` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TipoCurso_Estado`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Curso
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `programa` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `tipo_curso` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Curso_TipoCurso1`
    FOREIGN KEY (`tipo_curso`)
    REFERENCES `mydb`.`tipo_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla CursoAbierto
CREATE TABLE IF NOT EXISTS `mydb`.`Curso_abierto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inicio_inscripcion` DATETIME NOT NULL,
  `inicio_curso` DATETIME NOT NULL,
  `finalizacion_inscripcion` DATETIME NOT NULL,
  `finalizacion_curso` DATETIME NOT NULL,
  `pago_inicial` DECIMAL NOT NULL,
  `costo_total` DECIMAL NOT NULL,
   `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `horario` INT NOT NULL,
  `curso` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CursoAbierto_Horario1`
    FOREIGN KEY (`horario`)
    REFERENCES `mydb`.`Horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CursoAbierto_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CursoAbierto_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla PlanPago
CREATE TABLE IF NOT EXISTS `mydb`.`Plan_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plan_pago` VARCHAR(45) NOT NULL,
  `detalles` VARCHAR(255) NULL,
  `pago` INT(2) NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_PlanPago_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
-- Creación de la tabla Inscripcion
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NULL,
  `usuario` INT NOT NULL,
  `curso_abierto` INT NOT NULL,
  `plan_pago` INT NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Inscripcion_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_PlanPago1`
    FOREIGN KEY (`Plan_pago`)
    REFERENCES `mydb`.`Plan_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Asignatura
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asignatura` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Asignatura_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla AsignaturaCurso
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura_curso` (
  `asignatura` INT NOT NULL,
  `curso_abierto` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`asignatura`, `curso_abierto`),
  CONSTRAINT `fk_AsignaturaCurso_Asignatura1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `mydb`.`Asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaCurso_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaCurso_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla AsignaturaDocente
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura_docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `docente` INT NOT NULL,
  `asignatura` INT NOT NULL,
  `curso_abierto` INT NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_AsignaturaDocente_usuario1`
    FOREIGN KEY (`docente`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaDocente_Asignatura1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `mydb`.`Asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaDocente_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaDocente_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Actividad
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `curso_abierto` INT NOT NULL,
  `asignatura` INT NOT NULL,
  `cursoAbierto` INT NOT NULL,
  `asignatura_docente` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Actividad_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_AsignaturaCurso1`
    FOREIGN KEY (`asignatura` , `curso_abierto`)
    REFERENCES `mydb`.`Asignatura_curso` (`asignatura` , `curso_abierto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_AsignaturaDocente1`
    FOREIGN KEY (`asignatura_docente`)
    REFERENCES `mydb`.`Asignatura_docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Estudiante
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `actividad` TEXT NOT NULL,
  `comentario` TEXT NULL,
   `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `inscripcion` INT NOT NULL,
  `actividad_id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Estudiante_Inscripcion1`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `mydb`.`Actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Calificacion
CREATE TABLE IF NOT EXISTS `mydb`.`Calificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_grado` VARCHAR(45) NOT NULL,
  `numero_grado` DECIMAL(3,2) NOT NULL,
  `estudiante` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Calificacion_Estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `mydb`.`Estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Periodo
CREATE TABLE IF NOT EXISTS `mydb`.`Periodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Periodo_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resporte`
-- -----------------------------------------------------
-- Creación de la tabla Reporte
CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grado` DECIMAL NOT NULL,
  `gcomentario` VARCHAR(45) NULL,
  `ausencias` DECIMAL NOT NULL,
  `acomentario` VARCHAR(45) NULL,
  `comentario` VARCHAR(250) NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `docente` INT NOT NULL,
  `inscripcion` INT NOT NULL,
  `curso_abierto` INT NOT NULL,
  `asignatura` INT NOT NULL,
  `periodo` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Reporte_usuario1`
    FOREIGN KEY (`docente`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Inscripcion1`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Asignatura1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `mydb`.`Asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Periodo1`
    FOREIGN KEY (`periodo`)
    REFERENCES `mydb`.`Periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Evento
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evento` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `periodo` INT NOT NULL,
  `horario` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Evento_Periodo1`
    FOREIGN KEY (`periodo`)
    REFERENCES `mydb`.`Periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Horario1`
    FOREIGN KEY (`horario`)
    REFERENCES `mydb`.`Horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla EventoCurso
CREATE TABLE IF NOT EXISTS `mydb`.`Evento_curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `curso_abierto` INT NOT NULL,
  `evento` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_EventoCurso_CursoAbierto1`
    FOREIGN KEY (`curso_abierto`)
    REFERENCES `mydb`.`Curso_abierto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoCurso_Evento1`
    FOREIGN KEY (`evento`)
    REFERENCES `mydb`.`Evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoCurso_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Noticias
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `etiqueta` VARCHAR(30) NOT NULL,
  `noticia` TEXT NOT NULL,
  `imagen` TEXT NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `usuario` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Noticias_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla TipoRegistro
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_registro` VARCHAR(45) NOT NULL,
  `descripcion_registro` TEXT NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TipoRegistro_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Registro
CREATE TABLE IF NOT EXISTS `mydb`.`Registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` TIMESTAMP NOT NULL,
  `usuario` INT NOT NULL,
  `tipo_registro` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Registro_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_TipoRegistro1`
    FOREIGN KEY (`tipo_registro`)
    REFERENCES `mydb`.`Tipo_registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objetivo`
-- -----------------------------------------------------
-- Creación de la tabla Objetivo
CREATE TABLE IF NOT EXISTS `mydb`.`Objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(140) NOT NULL,
  `descripcion` TINYTEXT NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `asignatura` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Objetivo_Asignatura1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `mydb`.`Asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objetivo_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Pregunta
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(45) NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pregunta_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Cuenta
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `usuario` INT NOT NULL,
  `cuenta` VARCHAR(45) NOT NULL,
  `apodo` VARCHAR(45) NOT NULL,
  `imagen` TEXT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `pregunta` INT NOT NULL,
  PRIMARY KEY (`usuario`),
  CONSTRAINT `fk_Cuenta_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_Pregunta1`
    FOREIGN KEY (`pregunta`)
    REFERENCES `mydb`.`Pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Responsable
CREATE TABLE IF NOT EXISTS `mydb`.`Responsable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supervisor` INT NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Responsable_usuario1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsable_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Contraseña
CREATE TABLE IF NOT EXISTS `mydb`.`Contraseña` (
  `usuario` INT NOT NULL,
   salt BINARY(90) NOT NULL,
   hash BINARY(90) NOT NULL,
  `respuesta` BINARY(90) NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario`),
  CONSTRAINT `fk_Contraseña_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Notificacion
CREATE TABLE IF NOT EXISTS `mydb`.`Notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` INT(1) NOT NULL,
  `detalle` TEXT NOT NULL,
  `notificador` INT NOT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Notificacion_usuario1`
    FOREIGN KEY (`notificador`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_Estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Correo
CREATE TABLE IF NOT EXISTS `mydb`.`Correo` (
  `usuario` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `alteral` VARCHAR(45) NULL,
  `cpuntaje` INT(2) NULL,
   `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario`),
  CONSTRAINT `fk_Correo_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Telefono
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `usuario` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `alterno` VARCHAR(45) NULL,
  `whatsApp` INT(1) NOT NULL,
  `telegram` INT(1) NOT NULL,
  `otro` VARCHAR(45) NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_Telefono_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Descuento
CREATE TABLE IF NOT EXISTS `mydb`.`Descuento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descuento` VARCHAR(45) NOT NULL,
  `tipo_descuento` INT(1) NOT NULL,
  `monto` DECIMAL(9,2) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Descuento_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DescuentoInscripcion`
-- -----------------------------------------------------
-- Creación de la tabla DescuentoInscripcion
CREATE TABLE IF NOT EXISTS `mydb`.`Descuento_inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalles` VARCHAR(255) NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `inscripcion` INT NOT NULL,
  `descuento` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_DescuentoInscripcion_Inscripcion1`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DescuentoInscripcion_Descuento1`
    FOREIGN KEY (`descuento`)
    REFERENCES `mydb`.`Descuento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DescuentoInscripcion_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla TipoPago
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TipoPago_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla Pago
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(9,2) NOT NULL,
  `comprobante` TEXT NOT NULL,
  `descripcion` TINYTEXT NULL,
 `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `tipo_pago` INT NOT NULL,
  `inscripcion` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pago_TipoPago1`
    FOREIGN KEY (`tipo_pago`)
    REFERENCES `mydb`.`Tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Inscripcion1`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Creación de la tabla HistorialEstudiante
CREATE TABLE IF NOT EXISTS `mydb`.`Historial_estudiante` (
  `inscripcion` INT NOT NULL,
  `registro` TEXT NOT NULL,
  `creado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`inscripcion`),
  CONSTRAINT `fk_HistorialEstudiante_Inscripcion1`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




-- -------------------------------------
-- tipos de usuario activos 
-- ---------------------------------------
-- SELECT tu.id, 
   --    CASE e.estado
     --      WHEN 'activo' THEN 'Activo'
       --    ELSE 'Inactivo'
    --   END AS estado,
      -- tu.tipoUsuario
-- FROM TipoUsuario tu
-- INNER JOIN Estado e ON tu.Estado_id = e.id; 


-- SELECT 
   -- tu.id,
 --   tu.tipo_usuario,
--    tu.creado,
--    tu.modificado,
 --   e.estado AS estado_id
--   FROM 
  --  tipo_usuario tu
-- INNER JOIN 
  --  Estado e ON tu.estado_id = e.id
 -- WHERE 
   -- tu.estado_id = 1;
